pipeline {

    agent any

    stages {

        stage('Checkout Source...'){
            steps{
                git 'https://github.com/DiegoRestrepo1998/configserver.git'
            }
        }

        stage('Build Image...'){
            steps {
                script {
                    // Definir la etiqueta de la imagen en Docker Hub
                    def dockerTag = 'dfrestrepo1998/microservicio_configserver:1.0.0'
                    
                    // Construir la imagen de Docker usando la etiqueta especificada
                    docker.build dockerTag, '-f Dockerfile .'
                    
                    // Empujar la imagen al Docker Hub
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        docker.image(dockerTag).push()
                    }
                }
            }
        }
        stage('Deploying App to Kubernetes') {
            steps {
                script {
                    kubernetesDeploy(configs: "configserver_deploy.yml",kubeconfigId: "kubernetes")
                }
            }
        }
    
    }
}